namespace ClearDashboard.DataAccessLayer.Models.Helpers
{
    public static class BibleRefUtils
    {
        public static string GetBookNumFromBookName(string value)
        {
            Dictionary<string, string> lookup = new Dictionary<string, string>
            {
            { "GEN", "001" },
            { "EXO", "002" },
            { "LEV", "003" },
            { "NUM", "004" },
            { "DEU", "005" },
            { "JOS", "006" },
            { "JDG", "007" },
            { "RUT", "008" },
            { "1SA", "009" },
            { "2SA", "010" },
            { "1KI", "011" },
            { "2KI", "012" },
            { "1CH", "013" },
            { "2CH", "014" },
            { "EZR", "015" },
            { "NEH", "016" },
            { "EST", "017" },
            { "JOB", "018" },
            { "PSA", "019" },
            { "PRO", "020" },
            { "ECC", "021" },
            { "SNG", "022" },
            { "ISA", "023" },
            { "JER", "024" },
            { "LAM", "025" },
            { "EZK", "026" },
            { "DAN", "027" },
            { "HOS", "028" },
            { "JOL", "029" },
            { "AMO", "030" },
            { "OBA", "031" },
            { "JON", "032" },
            { "MIC", "033" },
            { "NAM", "034" },
            { "HAB", "035" },
            { "ZEP", "036" },
            { "HAG", "037" },
            { "ZEC", "038" },
            { "MAL", "039" },
            { "MAT", "040" },
            { "MRK", "041" },
            { "LUK", "042" },
            { "JHN", "043" },
            { "ACT", "044" },
            { "ROM", "045" },
            { "1CO", "046" },
            { "2CO", "047" },
            { "GAL", "048" },
            { "EPH", "049" },
            { "PHP", "050" },
            { "COL", "051" },
            { "1TH", "052" },
            { "2TH", "053" },
            { "1TI", "054" },
            { "2TI", "055" },
            { "TIT", "056" },
            { "PHM", "057" },
            { "HEB", "058" },
            { "JAS", "059" },
            { "1PE", "060" },
            { "2PE", "061" },
            { "1JN", "062" },
            { "2JN", "063" },
            { "3JN", "064" },
            { "JUD", "065" },
            { "REV", "066" },

            { "Genesis", "001" },
            { "Exodus", "002" },
            { "Leviticus", "003" },
            { "Numbers", "004" },
            { "Deuteronomy", "005" },
            { "Joshua", "006" },
            { "Judges", "007" },
            { "Ruth", "008" },
            { "1 Samuel", "009" },
            { "2 Samuel", "010" },
            { "1 Kings", "011" },
            { "2 Kings", "012" },
            { "1 Chronicles", "013" },
            { "2 Chronicles", "014" },
            { "Ezra", "015" },
            { "Nehemiah", "016" },
            { "Esther", "017" },
            { "Job", "018" },
            { "Psalms", "019" },
            { "Proverbs", "020" },
            { "Ecclesiastes", "021" },
            { "Song of Songs", "022" },
            { "Isaiah", "023" },
            { "Jeremiah", "024" },
            { "Lamentations", "025" },
            { "Ezekiel", "026" },
            { "Daniel", "027" },
            { "Hosea", "028" },
            { "Joel", "029" },
            { "Amos", "030" },
            { "Obadiah", "031" },
            { "Jonah", "032" },
            { "Micah", "033" },
            { "Nahum", "034" },
            { "Habakkuk", "035" },
            { "Zephaniah", "036" },
            { "Haggai", "037" },
            { "Zechariah", "038" },
            { "Malachi", "039" },
            { "Matthew", "040" },
            { "Mark", "041" },
            { "Luke", "042" },
            { "John", "043" },
            { "Acts", "044" },
            { "Romans", "045" },
            { "1 Corinthians", "046" },
            { "2 Corinthians", "047" },
            { "Galatians", "048" },
            { "Ephesians", "049" },
            { "Philippians", "050" },
            { "Colossians", "051" },
            { "1 Thessalonians", "052" },
            { "2 Thessalonians", "053" },
            { "1 Timothy", "054" },
            { "2 Timothy", "055" },
            { "Titus", "056" },
            { "Philemon", "057" },
            { "Hebrews", "058" },
            { "James", "059" },
            { "1 Peter", "060" },
            { "2 Peter", "061" },
            { "1 John", "062" },
            { "2 John", "063" },
            { "3 John", "064" },
            { "Jude", "065" },
            { "Revelation", "066" },

            };

            string sTmp;
            try
            {
                sTmp = lookup[value];
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                sTmp = "";
            }

            return sTmp;
        }


        public static Dictionary<string, string> GetBookIdDictionary()
        {
            Dictionary<string, string> lookup = new Dictionary<string, string>
            {
                { "001", "GEN"},
                { "002", "EXO"},
                { "003", "LEV"},
                { "004", "NUM"},
                { "005", "DEU"},
                { "006", "JOS"},
                { "007", "JDG"},
                { "008", "RUT"},
                { "009", "1SA"},
                { "010", "2SA"},
                { "011", "1KI"},
                { "012", "2KI"},
                { "013", "1CH"},
                { "014", "2CH"},
                { "015", "EZR"},
                { "016", "NEH"},
                { "017", "EST"},
                { "018", "JOB"},
                { "019", "PSA"},
                { "020", "PRO"},
                { "021", "ECC"},
                { "022", "SNG"},
                { "023", "ISA"},
                { "024", "JER"},
                { "025", "LAM"},
                { "026", "EZK"},
                { "027", "DAN"},
                { "028", "HOS"},
                { "029", "JOL"},
                { "030", "AMO"},
                { "031", "OBA"},
                { "032", "JON"},
                { "033", "MIC"},
                { "034", "NAM"},
                { "035", "HAB"},
                { "036", "ZEP"},
                { "037", "HAG"},
                { "038", "ZEC"},
                { "039", "MAL"},
                { "040", "MAT"},
                { "041", "MRK"},
                { "042", "LUK"},
                { "043", "JHN"},
                { "044", "ACT"},
                { "045", "ROM"},
                { "046", "1CO"},
                { "047", "2CO"},
                { "048", "GAL"},
                { "049", "EPH"},
                { "050", "PHP"},
                { "051", "COL"},
                { "052", "1TH"},
                { "053", "2TH"},
                { "054", "1TI"},
                { "055", "2TI"},
                { "056", "TIT"},
                { "057", "PHM"},
                { "058", "HEB"},
                { "059", "JAS"},
                { "060", "1PE"},
                { "061", "2PE"},
                { "062", "1JN"},
                { "063", "2JN"},
                { "064", "3JN"},
                { "065", "JUD"},
                { "066", "REV"}
            };
            return lookup;
        }
    }
}
