// <auto-generated />
using System;
using ClearDashboard.DAL.Tests.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClearDashboard.DAL.Tests.Migrations
{
    [DbContext(typeof(TestContext))]
    partial class TestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("ClearDashboard.DAL.Tests.Models.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SyncId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("ClearDashboard.DAL.Tests.Models.GrandParent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SyncId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GrandParents");
                });

            modelBuilder.Entity("ClearDashboard.DAL.Tests.Models.Parent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GrandParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SyncId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GrandParentId");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("ClearDashboard.DAL.Tests.Models.Child", b =>
                {
                    b.HasOne("ClearDashboard.DAL.Tests.Models.Parent", null)
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("ClearDashboard.DAL.Tests.Models.Parent", b =>
                {
                    b.HasOne("ClearDashboard.DAL.Tests.Models.GrandParent", null)
                        .WithMany("Children")
                        .HasForeignKey("GrandParentId");
                });

            modelBuilder.Entity("ClearDashboard.DAL.Tests.Models.GrandParent", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ClearDashboard.DAL.Tests.Models.Parent", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
