//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearDashboard.Wpf.Application {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gitlab.cleardashboard.org/api/v4/")]
        public string GitRootUrl {
            get {
                return ((string)(this["GitRootUrl"]));
            }
            set {
                this["GitRootUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://collaborationapi.cleardashboard.org")]
        public string CollaborationRootUrl {
            get {
                return ((string)(this["CollaborationRootUrl"]));
            }
            set {
                this["CollaborationRootUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Gjg4AdLk5TVU02iIdOPZFgbNqsXxSZJXKxGuGPhoCZuZ/Jgd/nQs8Zlx9ni+TBFXZEnwUjB4TQT085Oxnwq7rhdII2mUFS28DhCJUkF36mQI7RBRzJOwSPF42QA1iQCqH9A235Li4nzLdtu/VEfNQ63dW40bA/TWM5IbSL426aBvJeg30iJzFWP4XR/poqSrAaCWZya5F6d7Cvcwx+5/Pq6G+jfdk9bNp6vQwtVdpgStFRY1uS6dLX1hXn73sdZjHsS4+587e5MnROMT0LUWeiDjzvWMJ1Mm/dWBGl040tdOr2VngGpuHqWULb1V4KcS+KqNPqZY4Ugqayr7Noo4KzOrdelFpTci7euVtyG5z2SbxXDmqe8Xgbj2TLMVkjEjt68wKdq6pfsgCaZFJeTwhV2jO7/uKOZOImUlwBpGmqm/18KuLJK/NH03ApsyFU2fplxczyfDO/y3WV3o1G6RqugTKdjLU/GJgDjwhyYYsxaIKDBd0Ie+wm6QKDBZ+OLMa9jvat0AfvqXDI7qkmgq8HGalEMNWPfY+RrV7BvIDnJ0wMP5kUWbtgqwP5CIsS0++cLHOyV1dsFh/QwBoFDYHmO5Qvv4D4DeocUmfPVbjpO2hKKGl7BP+7+ctFRozrWmjVTRXkkLGT5cf+K7CRbdv+gBMZaYTGlsxzKr24GuiMNJlCYkrj9dfXMBomkG8DG4NwJGx+v110W7FaOHkcmc1qlwqMd882i8HRnvE+TPw9wPUXkEmvxnkyksjLqkI+Rd")]
        public string BearerTokenEncrypted {
            get {
                return ((string)(this["BearerTokenEncrypted"]));
            }
            set {
                this["BearerTokenEncrypted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAlignmentEditingEnabled {
            get {
                return ((bool)(this["IsAlignmentEditingEnabled"]));
            }
            set {
                this["IsAlignmentEditingEnabled"] = value;
            }
        }
    }
}
