using System.Collections.Generic;

namespace ClearDashboard.Wpf.Application.Helpers
{
    public static class Punctuation
    {
        public static List<string> LoadPunctuation()
        {
            List<string> puncs = new List<string>();
            puncs.Add(@"(");
            puncs.Add(@")");
            puncs.Add(@"‘");
            puncs.Add(@"[");
            puncs.Add(@"?");
            puncs.Add(@"]");
            puncs.Add(@"!");
            puncs.Add(@")");
            puncs.Add(@":");
            puncs.Add(@"’");
            puncs.Add(@"—");
            puncs.Add(@")");
            puncs.Add(@";");
            puncs.Add(@"”");
            puncs.Add(@"“");
            puncs.Add("\"");
            puncs.Add(@".");
            puncs.Add(@",");
            puncs.Add(@"？");
            puncs.Add(@"！");
            puncs.Add(@"：");
            puncs.Add(@"’");
            puncs.Add(@"”");
            puncs.Add(@"“");
            puncs.Add(@"，");
            puncs.Add(@"——");
            puncs.Add(@"‘");
            puncs.Add(@"。");
            puncs.Add(@"、");
            puncs.Add(@"；");
            puncs.Add(@"（");
            puncs.Add(@"》");
            puncs.Add(@"）");
            puncs.Add(@"《");
            puncs.Add(@"［");
            puncs.Add(@"。");
            puncs.Add(@"、");
            puncs.Add(@"〕");
            puncs.Add(@"」");
            puncs.Add(@"「");
            puncs.Add(@"/");
            puncs.Add(@"『");
            puncs.Add(@"?");
            puncs.Add(@"〔");
            puncs.Add(@"］");
            puncs.Add(@"』");
            puncs.Add(@",,");
            puncs.Add(@"‘‘");
            puncs.Add(@"’’’");
            puncs.Add(@"''");
            puncs.Add(@"-");
            puncs.Add(@"""""");
            puncs.Add(@"&");
            puncs.Add(@"{");
            puncs.Add(@"}");
            puncs.Add(@"*");
            puncs.Add(@"…");
            puncs.Add(@"_");
            puncs.Add(@"_​");
            puncs.Add(@"…");
            puncs.Add(@"°");
            puncs.Add(@"«");
            puncs.Add(@"»");
            puncs.Add(@"<");
            puncs.Add(@">");
            puncs.Add(@"#");
            puncs.Add(@"+");
            puncs.Add(@"=");
            puncs.Add(@"|");
            puncs.Add(@"\");
            puncs.Add(@"@");
            puncs.Add(@".");
            puncs.Add(@"¡!");
            puncs.Add(@"¿?");
            puncs.Add(@"¡");
            puncs.Add(@"¿");
            puncs.Add(@"…");
            puncs.Add(@"~");
            puncs.Add(@"،");
            puncs.Add(@"।");
            puncs.Add(@"॥");
            puncs.Add(@":-");
            puncs.Add(@"·");
            puncs.Add(@"〜");
            puncs.Add(@"【");
            puncs.Add(@"】");
            puncs.Add(@"・");
            puncs.Add(@"⟨");
            puncs.Add(@"⟩");
            puncs.Add(@"„");
            puncs.Add(@"‚");
            puncs.Add(@"–");
            puncs.Add(@"•");
            puncs.Add(@"≈");
            puncs.Add(@"×");
            puncs.Add(@"%");
            puncs.Add(@"<<");
            puncs.Add(@">>");
            puncs.Add(@"<");
            puncs.Add(@">");

            return puncs;
        }
    }
}
