// <auto-generated />
using System;
using ClearDashboard.DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClearDashboard.DataAccessLayer.Data.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Adornment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lemma")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartsOfSpeech")
                        .HasColumnType("TEXT");

                    b.Property<string>("Strong")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TokenId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenMorphology")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Adornment");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Alignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AlignmentOriginatedFrom")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AlignmentSetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AlignmentVerification")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<Guid>("SourceTokenComponentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetTokenComponentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlignmentSetId");

                    b.HasIndex("SourceTokenComponentId");

                    b.HasIndex("TargetTokenComponentId");

                    b.HasIndex("UserId");

                    b.ToTable("Alignment");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.AlignmentSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSymmetrized")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSyntaxTreeAlignerRefined")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ParallelCorpusHistoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParallelCorpusId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtModel")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParallelCorpusHistoryId");

                    b.HasIndex("ParallelCorpusId");

                    b.HasIndex("UserId");

                    b.ToTable("AlignmentSet");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.AlignmentSetDenormalizationTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlignmentSetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlignmentSetId");

                    b.ToTable("AlignmentSetDenormalizationTask");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.AlignmentTopTargetTrainingText", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlignmentSetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceTokenComponentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceTrainingText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TopTargetTrainingText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceTokenComponentId");

                    b.HasIndex("AlignmentSetId", "SourceTokenComponentId");

                    b.HasIndex("AlignmentSetId", "SourceTrainingText");

                    b.ToTable("AlignmentTopTargetTrainingText");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Corpus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CorpusType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FontFamily")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRtl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParatextGuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Corpus");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.CorpusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CorpusType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRtl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParatextGuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CorpusHistory");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Text")
                        .IsUnique();

                    b.ToTable("Label");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.LabelGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LabelGroup");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.LabelGroupAssociation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LabelGroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LabelGroupId");

                    b.HasIndex("LabelId");

                    b.ToTable("LabelGroupAssociation");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.LabelNoteAssociation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LabelId");

                    b.HasIndex("NoteId");

                    b.ToTable("LabelNoteAssociation");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Lexicon_Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LexemeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LexemeId");

                    b.HasIndex("UserId");

                    b.ToTable("Lexicon_Form");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Lexicon_Lexeme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lemma")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Lemma", "Type", "Language")
                        .IsUnique();

                    b.ToTable("Lexicon_Lexeme");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Lexicon_Meaning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LexemeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LexemeId");

                    b.HasIndex("UserId");

                    b.ToTable("Lexicon_Meaning");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Lexicon_SemanticDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Lexicon_SemanticDomain");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Lexicon_SemanticDomainMeaningAssociation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MeaningId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SemanticDomainId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeaningId");

                    b.HasIndex("SemanticDomainId");

                    b.ToTable("Lexicon_SemanticDomainMeaningAssociation");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Lexicon_Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MeaningId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginatedFrom")
                        .HasColumnType("jsonb");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeaningId");

                    b.HasIndex("UserId");

                    b.ToTable("Lexicon_Translation");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AbbreviatedText")
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Modified")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ThreadId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.NoteAssociation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssociationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssociationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NoteAssociation");

                    b.HasDiscriminator<string>("AssociationType").HasValue("NoteAssociation");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.NoteDomainEntityAssociation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DomainEntityIdGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainEntityIdName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("NoteDomainEntityAssociation");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.NoteRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NoteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.HasIndex("UserId");

                    b.ToTable("NoteRecipient");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.NoteUserSeenAssociation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.HasIndex("UserId");

                    b.ToTable("NoteUserSeenAssociation");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.ParallelCorpus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SourceTokenizedCorpusId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetTokenizedCorpusId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceTokenizedCorpusId");

                    b.HasIndex("TargetTokenizedCorpusId");

                    b.HasIndex("UserId");

                    b.ToTable("ParallelCorpus");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.ParallelCorpusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SourceTokenizedCorpusId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetTokenizedCorpusId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceTokenizedCorpusId");

                    b.HasIndex("TargetTokenizedCorpusId");

                    b.HasIndex("UserId");

                    b.ToTable("ParallelCorpusHistory");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppVersion")
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DesignSurfaceLayout")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRtl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastMergedCommitSha")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowTabLayout")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.RawContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Bytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NoteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("RawContent");

                    b.HasDiscriminator<string>("ContentType").HasValue("RawContent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TokenComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineTokenId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtendedProperties")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurfaceText")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TokenizedCorpusId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainingText")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VerseRowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EngineTokenId");

                    b.HasIndex("TokenizedCorpusId");

                    b.HasIndex("VerseRowId");

                    b.ToTable("TokenComponent");

                    b.HasDiscriminator<string>("Discriminator").HasValue("TokenComponent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TokenCompositeTokenAssociation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TokenCompositeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenCompositeId");

                    b.HasIndex("TokenId");

                    b.ToTable("TokenCompositeTokenAssociation");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TokenVerseAssociation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TokenComponentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VerseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenComponentId");

                    b.HasIndex("UserId");

                    b.HasIndex("VerseId");

                    b.ToTable("TokenVerseAssociation");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TokenizedCorpus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CorpusHistoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CorpusId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomVersData")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastTokenized")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ScrVersType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenizationFunction")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorpusHistoryId");

                    b.HasIndex("CorpusId");

                    b.HasIndex("UserId");

                    b.ToTable("TokenizedCorpus");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LexiconTranslationId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Modified")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SourceTokenComponentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetText")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TranslationSetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TranslationState")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LexiconTranslationId");

                    b.HasIndex("SourceTokenComponentId");

                    b.HasIndex("TranslationSetId");

                    b.HasIndex("UserId");

                    b.ToTable("Translation");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TranslationModelEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceText")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TranslationSetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TranslationSetId", "SourceText")
                        .IsUnique();

                    b.ToTable("TranslationModelEntry");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TranslationModelTargetTextScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TranslationModelEntryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TranslationModelEntryId", "Text")
                        .IsUnique();

                    b.ToTable("TranslationModelTargetTextScore");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TranslationSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlignmentSetId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DerivedFromId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ParallelCorpusHistoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParallelCorpusId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlignmentSetId");

                    b.HasIndex("DerivedFromId");

                    b.HasIndex("ParallelCorpusHistoryId");

                    b.HasIndex("ParallelCorpusId");

                    b.HasIndex("UserId");

                    b.ToTable("TranslationSet");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultLabelGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastAlignmentLevelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Verse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BBBCCCVVV")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BookNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChapterNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CorpusHistoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CorpusId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ParallelCorpusId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VerseMappingId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VerseNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerseText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BBBCCCVVV");

                    b.HasIndex("BookNumber");

                    b.HasIndex("ChapterNumber");

                    b.HasIndex("CorpusHistoryId");

                    b.HasIndex("CorpusId");

                    b.HasIndex("ParallelCorpusId");

                    b.HasIndex("UserId");

                    b.HasIndex("VerseMappingId");

                    b.HasIndex("VerseNumber");

                    b.ToTable("Verse");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.VerseMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParallelCorpusHistoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParallelCorpusId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParallelCorpusHistoryId");

                    b.HasIndex("ParallelCorpusId");

                    b.HasIndex("UserId");

                    b.ToTable("VerseMapping");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.VerseRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BookChapterVerse")
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmpty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInRange")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRangeStart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSentenceStart")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Modified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalText")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TokenizedCorpusId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookChapterVerse");

                    b.HasIndex("TokenizedCorpusId");

                    b.HasIndex("UserId");

                    b.ToTable("VerseRow");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.AlignmentAssociation", b =>
                {
                    b.HasBaseType("ClearDashboard.DataAccessLayer.Models.NoteAssociation");

                    b.HasDiscriminator().HasValue("AlignmentAssociation");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.BookAssociation", b =>
                {
                    b.HasBaseType("ClearDashboard.DataAccessLayer.Models.NoteAssociation");

                    b.HasDiscriminator().HasValue("BookAssociation");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.ChapterAssociation", b =>
                {
                    b.HasBaseType("ClearDashboard.DataAccessLayer.Models.NoteAssociation");

                    b.HasDiscriminator().HasValue("ChapterAssociation");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TokenAssociation", b =>
                {
                    b.HasBaseType("ClearDashboard.DataAccessLayer.Models.NoteAssociation");

                    b.HasDiscriminator().HasValue("TokenAssociation");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.VerseAssociation", b =>
                {
                    b.HasBaseType("ClearDashboard.DataAccessLayer.Models.NoteAssociation");

                    b.HasDiscriminator().HasValue("VerseAssociation");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.BinaryContent", b =>
                {
                    b.HasBaseType("ClearDashboard.DataAccessLayer.Models.RawContent");

                    b.HasDiscriminator().HasValue("BinaryContent");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.StringContent", b =>
                {
                    b.HasBaseType("ClearDashboard.DataAccessLayer.Models.RawContent");

                    b.HasDiscriminator().HasValue("StringContent");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Token", b =>
                {
                    b.HasBaseType("ClearDashboard.DataAccessLayer.Models.TokenComponent");

                    b.Property<int>("BookNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubwordNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VerseNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WordNumber")
                        .HasColumnType("INTEGER");

                    b.HasIndex("BookNumber");

                    b.HasIndex("ChapterNumber");

                    b.HasIndex("TrainingText");

                    b.HasIndex("VerseNumber");

                    b.ToTable("TokenComponent", (string)null);

                    b.HasDiscriminator().HasValue("Token");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TokenComposite", b =>
                {
                    b.HasBaseType("ClearDashboard.DataAccessLayer.Models.TokenComponent");

                    b.Property<Guid?>("ParallelCorpusId")
                        .HasColumnType("TEXT");

                    b.HasIndex("ParallelCorpusId");

                    b.ToTable("TokenComponent", (string)null);

                    b.HasDiscriminator().HasValue("TokenComposite");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Adornment", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.Token", "Token")
                        .WithOne("Adornment")
                        .HasForeignKey("ClearDashboard.DataAccessLayer.Models.Adornment", "TokenId");

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Alignment", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.AlignmentSet", "AlignmentSet")
                        .WithMany("Alignments")
                        .HasForeignKey("AlignmentSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.TokenComponent", "SourceTokenComponent")
                        .WithMany("SourceAlignments")
                        .HasForeignKey("SourceTokenComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.TokenComponent", "TargetTokenComponent")
                        .WithMany("TargetAlignments")
                        .HasForeignKey("TargetTokenComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlignmentSet");

                    b.Navigation("SourceTokenComponent");

                    b.Navigation("TargetTokenComponent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.AlignmentSet", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.ParallelCorpusHistory", null)
                        .WithMany("AlignmentSets")
                        .HasForeignKey("ParallelCorpusHistoryId");

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.ParallelCorpus", "ParallelCorpus")
                        .WithMany("AlignmentSets")
                        .HasForeignKey("ParallelCorpusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany("AlignmentSets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParallelCorpus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.AlignmentSetDenormalizationTask", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.AlignmentSet", "AlignmentSet")
                        .WithMany()
                        .HasForeignKey("AlignmentSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlignmentSet");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.AlignmentTopTargetTrainingText", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.AlignmentSet", "AlignmentSet")
                        .WithMany()
                        .HasForeignKey("AlignmentSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.TokenComponent", "SourceTokenComponent")
                        .WithMany()
                        .HasForeignKey("SourceTokenComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlignmentSet");

                    b.Navigation("SourceTokenComponent");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Corpus", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.CorpusHistory", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.LabelGroupAssociation", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.LabelGroup", "LabelGroup")
                        .WithMany("LabelGroupAssociations")
                        .HasForeignKey("LabelGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.Label", "Label")
                        .WithMany("LabelGroupAssociations")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Label");

                    b.Navigation("LabelGroup");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.LabelNoteAssociation", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.Label", "Label")
                        .WithMany("LabelNoteAssociations")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.Note", "Note")
                        .WithMany("LabelNoteAssociations")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Label");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Lexicon_Form", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.Lexicon_Lexeme", "Lexeme")
                        .WithMany("Forms")
                        .HasForeignKey("LexemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lexeme");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Lexicon_Lexeme", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Lexicon_Meaning", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.Lexicon_Lexeme", "Lexeme")
                        .WithMany("Meanings")
                        .HasForeignKey("LexemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lexeme");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Lexicon_SemanticDomain", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Lexicon_SemanticDomainMeaningAssociation", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.Lexicon_Meaning", "Meaning")
                        .WithMany("SemanticDomainMeaningAssociations")
                        .HasForeignKey("MeaningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.Lexicon_SemanticDomain", "SemanticDomain")
                        .WithMany("SemanticDomainMeaningAssociations")
                        .HasForeignKey("SemanticDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meaning");

                    b.Navigation("SemanticDomain");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Lexicon_Translation", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.Lexicon_Meaning", "Meaning")
                        .WithMany("Translations")
                        .HasForeignKey("MeaningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meaning");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Note", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.NoteDomainEntityAssociation", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.Note", "Note")
                        .WithMany("NoteDomainEntityAssociations")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.NoteRecipient", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.Note", null)
                        .WithMany("NoteRecipients")
                        .HasForeignKey("NoteId");

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.NoteUserSeenAssociation", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.Note", "Note")
                        .WithMany("NoteUserSeenAssociations")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.ParallelCorpus", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.TokenizedCorpus", "SourceTokenizedCorpus")
                        .WithMany("SourceParallelCorpora")
                        .HasForeignKey("SourceTokenizedCorpusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.TokenizedCorpus", "TargetTokenizedCorpus")
                        .WithMany("TargetParallelCorpora")
                        .HasForeignKey("TargetTokenizedCorpusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceTokenizedCorpus");

                    b.Navigation("TargetTokenizedCorpus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.ParallelCorpusHistory", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.TokenizedCorpus", "SourceTokenizedCorpus")
                        .WithMany()
                        .HasForeignKey("SourceTokenizedCorpusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.TokenizedCorpus", "TargetTokenizedCorpus")
                        .WithMany()
                        .HasForeignKey("TargetTokenizedCorpusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceTokenizedCorpus");

                    b.Navigation("TargetTokenizedCorpus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Project", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.RawContent", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.Note", null)
                        .WithMany("ContentCollection")
                        .HasForeignKey("NoteId");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TokenComponent", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.TokenizedCorpus", "TokenizedCorpus")
                        .WithMany("TokenComponents")
                        .HasForeignKey("TokenizedCorpusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.VerseRow", "VerseRow")
                        .WithMany("TokenComponents")
                        .HasForeignKey("VerseRowId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TokenizedCorpus");

                    b.Navigation("VerseRow");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TokenCompositeTokenAssociation", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.TokenComposite", "TokenComposite")
                        .WithMany("TokenCompositeTokenAssociations")
                        .HasForeignKey("TokenCompositeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.Token", "Token")
                        .WithMany("TokenCompositeTokenAssociations")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");

                    b.Navigation("TokenComposite");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TokenVerseAssociation", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.TokenComponent", "TokenComponent")
                        .WithMany("TokenVerseAssociations")
                        .HasForeignKey("TokenComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.Verse", "Verse")
                        .WithMany("TokenVerseAssociations")
                        .HasForeignKey("VerseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TokenComponent");

                    b.Navigation("User");

                    b.Navigation("Verse");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TokenizedCorpus", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.CorpusHistory", "CorpusHistory")
                        .WithMany("TokenizedCorpora")
                        .HasForeignKey("CorpusHistoryId");

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.Corpus", "Corpus")
                        .WithMany("TokenizedCorpora")
                        .HasForeignKey("CorpusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corpus");

                    b.Navigation("CorpusHistory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Translation", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.Lexicon_Translation", "LexiconTranslation")
                        .WithMany()
                        .HasForeignKey("LexiconTranslationId");

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.TokenComponent", "SourceTokenComponent")
                        .WithMany("Translations")
                        .HasForeignKey("SourceTokenComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.TranslationSet", "TranslationSet")
                        .WithMany("Translations")
                        .HasForeignKey("TranslationSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LexiconTranslation");

                    b.Navigation("SourceTokenComponent");

                    b.Navigation("TranslationSet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TranslationModelEntry", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.TranslationSet", "TranslationSet")
                        .WithMany("TranslationModel")
                        .HasForeignKey("TranslationSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TranslationSet");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TranslationModelTargetTextScore", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.TranslationModelEntry", "TranslationModelEntry")
                        .WithMany("TargetTextScores")
                        .HasForeignKey("TranslationModelEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TranslationModelEntry");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TranslationSet", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.AlignmentSet", "AlignmentSet")
                        .WithMany()
                        .HasForeignKey("AlignmentSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.TranslationSet", "DerivedFrom")
                        .WithMany()
                        .HasForeignKey("DerivedFromId");

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.ParallelCorpusHistory", null)
                        .WithMany("TranslationSets")
                        .HasForeignKey("ParallelCorpusHistoryId");

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.ParallelCorpus", "ParallelCorpus")
                        .WithMany("TranslationSets")
                        .HasForeignKey("ParallelCorpusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany("TranslationSets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlignmentSet");

                    b.Navigation("DerivedFrom");

                    b.Navigation("ParallelCorpus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Verse", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.CorpusHistory", null)
                        .WithMany("Verses")
                        .HasForeignKey("CorpusHistoryId");

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.Corpus", "Corpus")
                        .WithMany()
                        .HasForeignKey("CorpusId");

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.ParallelCorpus", "ParallelCorpus")
                        .WithMany()
                        .HasForeignKey("ParallelCorpusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.VerseMapping", "VerseMapping")
                        .WithMany("Verses")
                        .HasForeignKey("VerseMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corpus");

                    b.Navigation("ParallelCorpus");

                    b.Navigation("User");

                    b.Navigation("VerseMapping");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.VerseMapping", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.ParallelCorpusHistory", null)
                        .WithMany("VerseMappings")
                        .HasForeignKey("ParallelCorpusHistoryId");

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.ParallelCorpus", "ParallelCorpus")
                        .WithMany("VerseMappings")
                        .HasForeignKey("ParallelCorpusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParallelCorpus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.VerseRow", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.TokenizedCorpus", "TokenizedCorpus")
                        .WithMany("VerseRows")
                        .HasForeignKey("TokenizedCorpusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearDashboard.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TokenizedCorpus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TokenComposite", b =>
                {
                    b.HasOne("ClearDashboard.DataAccessLayer.Models.ParallelCorpus", "ParallelCorpus")
                        .WithMany("TokenComposites")
                        .HasForeignKey("ParallelCorpusId");

                    b.Navigation("ParallelCorpus");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.AlignmentSet", b =>
                {
                    b.Navigation("Alignments");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Corpus", b =>
                {
                    b.Navigation("TokenizedCorpora");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.CorpusHistory", b =>
                {
                    b.Navigation("TokenizedCorpora");

                    b.Navigation("Verses");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Label", b =>
                {
                    b.Navigation("LabelGroupAssociations");

                    b.Navigation("LabelNoteAssociations");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.LabelGroup", b =>
                {
                    b.Navigation("LabelGroupAssociations");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Lexicon_Lexeme", b =>
                {
                    b.Navigation("Forms");

                    b.Navigation("Meanings");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Lexicon_Meaning", b =>
                {
                    b.Navigation("SemanticDomainMeaningAssociations");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Lexicon_SemanticDomain", b =>
                {
                    b.Navigation("SemanticDomainMeaningAssociations");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Note", b =>
                {
                    b.Navigation("ContentCollection");

                    b.Navigation("LabelNoteAssociations");

                    b.Navigation("NoteDomainEntityAssociations");

                    b.Navigation("NoteRecipients");

                    b.Navigation("NoteUserSeenAssociations");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.ParallelCorpus", b =>
                {
                    b.Navigation("AlignmentSets");

                    b.Navigation("TokenComposites");

                    b.Navigation("TranslationSets");

                    b.Navigation("VerseMappings");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.ParallelCorpusHistory", b =>
                {
                    b.Navigation("AlignmentSets");

                    b.Navigation("TranslationSets");

                    b.Navigation("VerseMappings");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TokenComponent", b =>
                {
                    b.Navigation("SourceAlignments");

                    b.Navigation("TargetAlignments");

                    b.Navigation("TokenVerseAssociations");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TokenizedCorpus", b =>
                {
                    b.Navigation("SourceParallelCorpora");

                    b.Navigation("TargetParallelCorpora");

                    b.Navigation("TokenComponents");

                    b.Navigation("VerseRows");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TranslationModelEntry", b =>
                {
                    b.Navigation("TargetTextScores");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TranslationSet", b =>
                {
                    b.Navigation("TranslationModel");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.User", b =>
                {
                    b.Navigation("AlignmentSets");

                    b.Navigation("TranslationSets");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Verse", b =>
                {
                    b.Navigation("TokenVerseAssociations");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.VerseMapping", b =>
                {
                    b.Navigation("Verses");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.VerseRow", b =>
                {
                    b.Navigation("TokenComponents");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.Token", b =>
                {
                    b.Navigation("Adornment");

                    b.Navigation("TokenCompositeTokenAssociations");
                });

            modelBuilder.Entity("ClearDashboard.DataAccessLayer.Models.TokenComposite", b =>
                {
                    b.Navigation("TokenCompositeTokenAssociations");
                });
#pragma warning restore 612, 618
        }
    }
}
