name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  Solution_Path: src\ClearDashboard.sln
  Test_Project_Path: src\ClearDashboard.CoreTests\ClearDashboard.CoreTests.csproj
  Wpf_Project_Path: src\ClearDashboard.WPF\ClearDashboard.WPF.csproj
  Wap_Project_Directory: ClearDashboard.WPF.Package
  Wap_Project_Name: ClearDashboard.WPF.Package.wapproj

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore $env:Solution_Path
    - name: Build
      run: dotnet build $env:Solution_Path --no-restore
    - name: Test
      run: dotnet test $env:Test_Project_Path --no-build --verbosity normal
